---
- name: Get cluster fsid
  ansible.builtin.command: cephadm shell -- ceph fsid
  when: cephadm_fsid | length == 0
  become: true
  register: cephadm_fsid_current
  changed_when: false

- name: Set fsid fact
  ansible.builtin.set_fact:
    fsid: "{{ cephadm_fsid if cephadm_fsid | length > 0 else cephadm_fsid_current.stdout }}"

- name: Template out placement-policy.json
  ansible.builtin.template:
    src: placement-policy.json.j2
    dest: "/var/run/ceph/{{ fsid }}/placement-policy.json"
    owner: root
    group: root
    mode: "0644"
  become: true
  when:
    - cephadm_rgw_placement_policies | length > 0
    - inventory_hostname == cephadm_bootstrap_host

- name: Apply placement policy
  ansible.builtin.command: >
    cephadm shell -- bash -c
    'radosgw-admin zone set < /var/run/ceph/placement-policy.json'
  become: true
  changed_when: true
  when:
    - cephadm_rgw_placement_policies | length > 0
    - inventory_hostname == cephadm_bootstrap_host
